[package]
name = "bevy_playground"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
bevy = "0.18.1"
astra_voxel_world = { path = "D:/git/Astra-Imperium/crates/astra_voxel_world" }
astra_camera = { path = "D:/git/Astra-Imperium/crates/astra_camera" }
astra_planet = { path = "D:/git/Astra-Imperium/crates/astra_planet" }
astra_render = { path = "D:/git/Astra-Imperium/crates/astra_render" }

[profile.dev]
debug = 0
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
